project_id = "yjfhuuovxhqpcpheivgv"

[functions.process-email-queue]
verify_jwt = true

[functions.oab-sync]
verify_jwt = false

[functions.cron-monitoramento]
verify_jwt = false

[functions.dje-discovery]
verify_jwt = false

[functions.dje-tjam-busca]
verify_jwt = false

[functions.busca-oab]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false