import { ExternalLink, Pencil, Star, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { classifyActivityDueDate, ACTIVITY_STATUS_LABELS } from "@/lib/activity-status";
import type { ActivityTeamMember, ActivityWithUserState } from "@/types/activities";

export function ActivityDetailSheet({ activity, members, onClose, onEdit, onFavorite, onDelete, onStatus }: { activity: ActivityWithUserState | null; members: ActivityTeamMember[]; onClose: () => void; onEdit: (activity: ActivityWithUserState) => void; onFavorite: (activity: ActivityWithUserState) => void; onDelete: (activity: ActivityWithUserState) => void; onStatus: (activity: ActivityWithUserState, status: string) => void }) {
  if (!activity) return null;
  const member = members.find(item => item.userId === activity.responsavel_id);
  const due = classifyActivityDueDate(activity.data_limite);
  return <Sheet open onOpenChange={open => { if (!open) onClose(); }}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><div className="mb-2 flex flex-wrap gap-2"><Badge>{ACTIVITY_STATUS_LABELS[activity.status as keyof typeof ACTIVITY_STATUS_LABELS] ?? activity.status}</Badge><Badge variant="outline">{activity.prioridade}</Badge>{activity.source_type ? <Badge variant="secondary">Origem: {activity.source_type}</Badge> : null}</div><SheetTitle>{activity.titulo}</SheetTitle><SheetDescription>{due.label ?? "Sem prazo definido"} · {member?.name ?? "Sem responsável"}</SheetDescription></SheetHeader><div className="mt-6 space-y-4 text-sm">{activity.descricao ? <p className="rounded-lg bg-muted/50 p-3">{activity.descricao}</p> : null}<dl className="grid grid-cols-2 gap-3 rounded-lg border p-3"><div><dt className="text-xs text-muted-foreground">Processo</dt><dd>{activity.process?.number ?? "Não vinculado"}</dd></div><div><dt className="text-xs text-muted-foreground">Cliente</dt><dd>{activity.process?.clientName ?? "Não informado"}</dd></div><div><dt className="text-xs text-muted-foreground">Categoria</dt><dd>{activity.categoria ?? "Sem categoria"}</dd></div><div><dt className="text-xs text-muted-foreground">Pontos</dt><dd>{activity.pontos}</dd></div></dl>{activity.processo_id ? <Button variant="outline" asChild className="w-full"><a href={`/processos/${activity.processo_id}`}>Abrir processo<ExternalLink className="ml-2 h-4 w-4" /></a></Button> : null}{activity.source_type === "publicacao" && activity.source_id ? <Button variant="outline" asChild className="w-full"><a href={`/publicacoes?publication=${activity.source_id}`}>Abrir publicação<ExternalLink className="ml-2 h-4 w-4" /></a></Button> : null}<div className="grid grid-cols-3 gap-2"><Button variant="outline" onClick={() => onStatus(activity, "pendente")}>A Fazer</Button><Button variant="outline" onClick={() => onStatus(activity, "em_andamento")}>Fazendo</Button><Button variant="outline" onClick={() => onStatus(activity, "concluída")}>Concluir</Button></div><div className="flex gap-2 border-t pt-4"><Button className="flex-1" onClick={() => onEdit(activity)}><Pencil className="mr-2 h-4 w-4" />Editar</Button><Button variant="outline" size="icon" onClick={() => onFavorite(activity)} aria-label="Favoritar"><Star className={`h-4 w-4 ${activity.userState?.favorita ? "fill-amber-400 text-amber-500" : ""}`} /></Button><Button variant="destructive" size="icon" onClick={() => onDelete(activity)} aria-label="Excluir"><Trash2 className="h-4 w-4" /></Button></div></div></SheetContent></Sheet>;
}
