import { useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { classifyActivityDueDate, ACTIVITY_STATUS_LABELS } from "@/lib/activity-status";
import type { ActivityStatus, ActivityTeamMember, ActivityWithUserState } from "@/types/activities";

const columns: ActivityStatus[] = ["pendente", "em_andamento", "em_revisao", "concluída"];

export function ActivityKanban({ activities, members, onOpen, onMove, onNew }: { activities: ActivityWithUserState[]; members: ActivityTeamMember[]; onOpen: (activity: ActivityWithUserState) => void; onMove: (activity: ActivityWithUserState, status: ActivityStatus) => void; onNew: (status: ActivityStatus) => void }) {
  const [dragId, setDragId] = useState<string | null>(null);
  return <div className="flex gap-4 overflow-x-auto pb-3">{columns.map(status => { const items = activities.filter(activity => activity.status === status); return <section key={status} className="min-h-[480px] min-w-[300px] flex-1 rounded-2xl bg-muted/30 p-3" onDragOver={event => event.preventDefault()} onDrop={() => { const activity = activities.find(item => item.id === dragId); if (activity) onMove(activity, status); setDragId(null); }}><header className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">{ACTIVITY_STATUS_LABELS[status]}</h2><span className="text-xs text-muted-foreground">{items.length} atividade(s)</span></div><Button size="icon" variant="ghost" onClick={() => onNew(status)} aria-label={`Criar em ${ACTIVITY_STATUS_LABELS[status]}`}><Plus className="h-4 w-4" /></Button></header><div className="space-y-2">{items.map(activity => { const member = members.find(item => item.userId === activity.responsavel_id); const due = classifyActivityDueDate(activity.data_limite); return <article key={activity.id} draggable onDragStart={() => setDragId(activity.id)} className="rounded-xl border bg-card p-3 shadow-sm"><button type="button" onClick={() => onOpen(activity)} className="w-full text-left"><p className="font-medium">{activity.titulo}</p><p className={`mt-1 text-xs ${due.urgent ? "text-destructive" : "text-muted-foreground"}`}>{due.label ?? "Sem prazo"} · {member?.name ?? "Sem responsável"}</p>{activity.process ? <p className="mt-1 truncate text-xs text-muted-foreground">{activity.process.number}{activity.process.clientName ? ` · ${activity.process.clientName}` : ""}</p> : null}</button><Select value={activity.status} onValueChange={value => onMove(activity, value as ActivityStatus)}><SelectTrigger className="mt-3 h-8 text-xs" aria-label={`Mover ${activity.titulo}`}><SelectValue /></SelectTrigger><SelectContent>{columns.map(option => <SelectItem key={option} value={option}>{ACTIVITY_STATUS_LABELS[option]}</SelectItem>)}</SelectContent></Select></article>; })}{!items.length ? <p className="py-12 text-center text-sm text-muted-foreground">Sem atividades</p> : null}</div></section>; })}</div>;
}

